pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'npm ci'
            }
        }

        stage('Verify Cypress') {
            steps {
                bat 'npx cypress verify'
            }
             }

        stage('Run Tests') {
            steps {
                bat 'npx cypress run'
            }
        }
        }
}