pipeline {
    agent any
    
    tools {
        nodejs 'Node-Latest' // This automatically adds node and npm to the system PATH
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('Cypress-Framework') {
                    sh 'npm ci'
                }
            }
        }

        stage('Verify Cypress') {
            steps {
                dir('Cypress-Framework') {
                    sh 'npx cypress verify'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('Cypress-Framework') {
                    sh 'npx cypress run'
                }
            }
        }
    }
}