pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                // Navigates into the subfolder where package.json lives
                dir('Cypress-Framework') {
                    sh 'npm ci'
                }
            }
        }

        stage('Verify Cypress') {
            steps {
                dir('Cypress-Framework') {
                    sh 'npx cypress verify'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('Cypress-Framework') {
                    sh 'npx cypress run'
                }
            }
        }
    }
}